version: '3'

services:
  workspace:
    build:
      context: ./code-server
      dockerfile: ./Dockerfile
    container_name: workspace-${WORKSPACE_NAME}
    privileged: true
    env_file:
      - .env
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - PASSWORD=${PASSWORD}
      - SHELL=/bin/bash
    restart: always
    volumes:
      - ${HOME}/${WORKSPACE_NAME}/.config:/home/${USERNAME}/.config
      - ${HOME}/${WORKSPACE_NAME}/.ssh:/home/${USERNAME}/.ssh
      - ${HOME}/${WORKSPACE_NAME}/projects:/home/${USERNAME}/projects
    user: ${CUID}:${CGID}
