version: '3'

services:
  workspace:
    build:
      context: ./code-server
      dockerfile: ./Dockerfile
      args:
        USERNAME: $USERNAME
        USER_UID: $CUID
        USER_GID: $CGID
        NODE_VERSION: $NODE_VERSION
    container_name: workspace-${WORKSPACE_NAME}
    privileged: true
    env_file:
      - .env
    ports:
      - 8080:8080
      - 3000:3000
      - 4080:4080
      - 4090:4090
      - 27017:27017
    environment:
      - PASSWORD=${PASSWORD}
      - SHELL=/bin/bash
    restart: always
    volumes:
      - ${HOME}/${WORKSPACE_NAME}/.config:/home/${USERNAME}/.config
      - ${HOME}/.ssh:/home/${USERNAME}/.ssh
      - ${HOME}/${WORKSPACE_NAME}/projects:/home/${USERNAME}/projects
      - docker:/var/lib/docker
    user: ${CUID}:${CGID}

volumes:
  docker:
